#
###################################
# Site wide configuration
####################################
#
title: olzhas
email: olzhas.adi@gmail.com
description: Personal webpage
url: https://olzhas.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Almaty
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Olzhas Adiyatov"
  avatar: avatar.jpg
  job: "MSc student"
  bio: ""
  email: olzhas.adi@gmail.com
  disqus-shortname: "https-olzhas-github-io"
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: "UA-43677697-3"
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: olzhas
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: OlzhasAdi
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
